version: '3.8'

services:
  app:
    build: .
    container_name: nextjs-app
    ports:
      - '4000:3000'
    environment:
      - MONGODB_URI=mongodb://root:example@localhost:27017/chatDatabase?authSource=admin
      - NEXT_PUBLIC_MONGODB_URI=mongodb://root:example@localhost:27017/chatDatabase?authSource=admin
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongo
    networks:
      - app-network
    command: >
      sh -c "
        npm run generate-jwt-secret &&
        npm run serverstart &
        npm run dev
      "

  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - mongo-data:/data/db
      - ./src/db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    networks:
      - app-network

volumes:
  mongo-data:
    driver: local

networks:
  app-network:
    driver: bridge