version: '3.8'

services:
  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - mongo-data:/data/db
       - ./src/db/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js
    networks:
      - app-network

volumes:
  mongo-data:
    driver: local

networks:
  app-network:
    driver: bridge