version: '3.8'

services:
  app:
    build: .
    container_name: nextjs-app
    ports:
      - '4000:3000'
    environment:
      - MONGODB_URI=mongodb://mongo:27017/chatDatabase
    depends_on:
      - mongo
    networks:
      - app-network
  mongo:
    image: mongo:6
    container_name: mongodb
    ports:
      - '27017:27017'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:
    driver: local

networks:
  app-network:
    driver: bridge